### ISSUE TITLE
Account field types

### ISSUE THREAD

**Issue by cedricpim** [barskern/firefly-iii-rs#3]
Hi there,

Do you know why in this struct: https://github.com/barskern/firefly-iii-rs/blob/master/src/models/account.rs#L17, the amount values are `f64`, when in https://github.com/firefly-iii/api-docs-generator/blob/main/yaml/schemas/Account.yaml, they are Strings? (One of the values was changed recently from `double` to `string`, but the others were already Strings.

**Comment by barskern** [comment]
I have to manually release a new version, so it's just that I have to ensure that I stay up to date with the latest documentation from firefly. In release v0.2.2 (which was just released), I've updated to version 1.3.0 of the API, hence this should be fixed. Thank you ! :smile:

**Comment by cedricpim** [comment]
@barskern Thanks. Although seems like `opening_balance` on Account is still marked as `f64` but should be a String I think.

And there is also this: https://github.com/firefly-iii/api-docs-generator/commit/24d95bbb44b0aa9032564384a0527b09767df13e, and that added variant is missing from: https://github.com/barskern/firefly-iii-rs/blob/master/src/models/transaction_split.rs#L239.

**Comment by barskern** [comment]
Ah I didn't see that there was a 1.4.0 version of the swagger documentation. I will generate and release a new version as soon as I have time! Thank you for the help. 😊

**Comment by barskern** [comment]
Sorry for the time delay, but I have now released v2.3.0 which is based on v1.4.0 (https://github.com/firefly-iii/api-docs/blob/main/firefly-iii-1.4.0.yaml). :smile: @cedricpim

**Comment by cedricpim** [comment]
Thank you :bow:
