### ISSUE TITLE
Open to doing an update?

### ISSUE THREAD

**Issue by GeorgeHahn** [barskern/firefly-iii-rs#4]
Hi, I'm using the ff3 API in a rust project I'm working on. The latest API spec (1.5.5) has quite a few usability improvements for generated clients and the latest openapi generator has some library updates. I also have a customized template that removes the boxing from every model field.

Would you mind reviewing a set of PRs with these changes? I will prepare some PRs if you are open to considering them.

**Comment by barskern** [comment]
> Would you mind reviewing a set of PRs with these changes? I will prepare some PRs if you are open to considering them.

I would love getting a PR for that. Thank you!

**Comment by GeorgeHahn** [comment]
Excellent! I'll send a PR shortly.
